spring.application.name=17-OpenAPI-Swagger
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=password


springdoc.swagger-ui.path=/my-ui.html

#if u wanna download doc use this endpoint ->/v3/api-docs.yaml

#Configure custom path for api docs

springdoc.api-docs.path=/my-api-docs



#simple spring security
spring.security.user.name=omer
spring.security.user.password=password