spring.application.name=03-Spring-Acuator-Demo
server.port=8081
#Use wilcard "*" to expose all endpoints
#Can also expose individual endpoints with a coma-delimited list
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=health,info
#open endpoints
management.info.env.enabled=true
info.app.name=My First Actuator App
info.app.description=This is a exmaple of Actuator
info.app.version=1.0.0



#Define properties

coach.name=Hacicavcav
team.name=The Cavcav Core



