spring.application.name=16-SpringBoot-Rest-CRUD-JPA


spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=root
spring.datasource.password=password

spring.data.rest.base-path=/magic-api
spring.data.rest.default-page-size=3